### ISSUE TITLE
Support subaddressing

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-lsc#17]
Subaddressing currently fails.

When synchronizing:

```
dn: uid=dsi.test2,ou=users,dc=example,dc=com
objectClass: pilotPerson
uid: dsi.test2
cn: Dsi TEST
sn: TEST
mail: dsi.test2@poc-mail-avocat.fr
otherMailbox: dsi.test+avecplus@cnb.avocat.fr
```

We get the following error.

`13:49:40.685 [ERROR] o.a.j.w.r.MailAddressParser - The target forward dsi.test+avecplus@cnb.avocat.fr is not an email address`

Please URL encode the resulting address.

EG bot bob+tag@b.com

```
http://localhost:43353/address/forwards/alice%40b.com/targets/bob%252Btag%2540b.com
```

Write a unit test for alias (IN the alias), group (if relevant), forward, and address sub-components.

Cc @quantranhong1999

**Comment by quantranhong1999** [comment]
Should need https://github.com/linagora/james-project/issues/4854 to work on James' side first, so easier to test on the LSC side, no?

Or do you just need a unit test upon URL encoding in LSC?

**Comment by quantranhong1999** [comment]
I found it weird when James needs double decoding of the URL path (1 round of decoding by Spark already and another round by `MailAddressParser.parseMailAddress`). 

FYI the Rest Assured client automatically encodes the URL path -> we have 2 times of encoding in the subAddressing unit test in James -> which is why the test passed.

I am not sure if that is intended, or there is a rationale behind that I do not know.

At least now I would go for double URL encoding in LSC then.

**Comment by chibenwa** [comment]
... That could be caused by restassured encoding one more time...

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/issues/4855

**Comment by quantranhong1999** [comment]
We still need to encode 1 time on LSC, no? Or do you want to create another ticket? :)

**Comment by quantranhong1999** [comment]
(LSC uses Jersey client that does not have auto encoding)

**Comment by chibenwa** [comment]
> We still need to encode 1 time on LSC, no? 

YES!

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-lsc/pull/18
